model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
tokenizer_name: meta-llama/Meta-Llama-3.1-8B-Instruct
padding_side: right
task_type: CAUSAL_LM
peft_config:
  task_type: CAUSAL_LM
  r: 32
  lora_alpha: 64
  lora_dropout: 0.1
  bias: none
  modules_to_save: 
    - special_tokens
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
